const express = require("express");
const app = express();
const register = require("./register");
const login = require("./login");
const logout = require("./logout");
const changePass = require("./changePass");
const verify = require("./verify");
const request = require("./request");
app.use("/register", register);
app.use("/login", login);
app.use("/logout", logout);
app.use("/verify", verify);
app.use("/request", request);
app.use("/changePass", changePass);
module.exports = app;
